### ISSUE TITLE
--assembly option does not work

### ISSUE THREAD

**Issue by Kincekara** [appliedbinf/el_gato#12] opened 2023-12-11 15:25 UTC
Hi,
The program exits when only assembly is provided.

"Read file 1: ('None') and Read file 2: ('None') are the same. Exiting"

I think input check at lines [561-565](https://github.com/appliedbinf/el_gato/blob/905b72b468773ab60a8c467e5b86ffa523298949/el_gato/el_gato.py#L561C1-L564C120) cause the issue.

**Comment by Alan-Collins** [comment] 2023-12-11 16:20
You are right about the cause. I just pushed a fix. Thanks!

**Closed as completed by Alan-Collins** 2023-12-11 16:20 UTC
