### ISSUE TITLE
Found conflicts! Looking for incompatible packages

### ISSUE THREAD

**Issue by tbazilegith** [appliedbinf/el_gato#2] opened 2023-05-18 19:14 UTC
Hi,
I've been trying to install el_gato, ran into issues.
I used the conda installation
conda create -n elgato -c bioconda -c conda-forge -c appliedbinf elgato
but got this:

Found conflicts! Looking for incompatible packages.                                                                                                                                                                                          iled
Examining @/linux-64::__archspec==1=x86_64:  80%|ââââââââââââââââââââââââââââââ
UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisf
Any ideas?
TJ

**Comment by Alan-Collins** [comment] 2023-05-18 23:34
Hi TJ, 

Would you mind providing some more information about your setup?

1. What kind of system are you on (e.g., linux, mac)? 
   a) If linux, which distro and is it and is it a system install or Windows Subsystem for Linux? 
   b) If mac are you using a newer laptop with an M1 chip?
2. Are you using miniconda or anaconda? Which conda version?
3. Are you able to install other conda packages?
 
Thanks,
Alan

**Comment by tbazilegith** [comment] 2023-05-24 14:42
Hi Alan,
My system in linux, and it's on an HPC cluster.  What is distro
Thanks,
Tassy
________________________________

**Comment by Alan-Collins** [comment] 2023-05-24 18:34
A distro is a linux distribution like Ubuntu.
Which conda version are you using?
Are you able to install other things using conda?

**Comment by tbazilegith** [comment] 2023-05-26 06:35
Hi Alan,
The conda version is

conda/23.3.1


Yes, I install software using conda.

Thanks!

________________________________

**Comment by Alan-Collins** [comment] 2023-05-26 16:07
Hi Tassy,

Thanks for the information. I am able to install el_gato without issue with that conda version on the HPC cluster that I have access to.

As I am not able to reproduce the error and the error message itself doesn't describe a specific issue, I think your best bet will be to submit a ticket with the support team for your HPC cluster. Would you mind reaching out to them and then letting us know what they say?

Thanks,
Alan

**Comment by tbazilegith** [comment] 2023-05-30 20:27
Hi Alan,
Thanks for the responses. 
Firstly, I ran the script el_gato.py in a sbatch:
for samp in $(cat samples.txt); do
  /home/el_gato/el_gato.py --assembly ../assemblies/${samp}_assembly.fasta --out output2019_mlst
done
- my sbatch script failed, but the outdir looked like this
identified_alleles.fna  intermediate_outputs.txt  possible_mlsts.txt  run.log
less possible_mlsts.tx
Sample  ST      flaA    pilE    asd     mip     mompS   proA    neuA_neuAH
JBA19001326_assembly    Novel ST*       30      60*     43*     61      15*     29*     233*
- Any ideas about why the sbatch script failed?

- Secondly, I cloned the repository so I use nextflow and ran the command below

 nextflow /user/repos/el_gato4mlst/el_gato/run_el_gato.nf --assembly_dir ../assemblies/*.fasta --out output2019_mlst01 -profile singularity -c /user/repos/el_gato4mlst/el_gato/nextflow.config

but I got this error:

ERROR ~ Error executing process > 'RUN_EL_GATO_ASSEMBLIES (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name vchivukula-collection-elgato-latest.img.pulling.1685477123508 library://vchivukula/collection/elgato:latest > /dev/null
  status : 255
  message:
    FATAL:   Unable to get library client configuration: remote has no library client (see https://apptainer.org/docs/user/latest/endpoint.html#no-default-remote)

 -- Check '.nextflow.log' file for details
- There seems to be an issue with the library - Any ideas?
-Thanks!
TJ

**Comment by Alan-Collins** [comment] 2023-06-01 19:50
Hi TJ,

I don't know why your sbatch script failed. It looks like it ran successfully on a sample as you have the expected output files. If you ran el_gato on multiple samples then the issue will be that you provided the same output folder for each. el_gato writes output files with the same name each run so you need to provide a different output folder per sample. el_gato can replace an existing output folder if you use the overwrite mode with `-w`.

The error message contains a link to the apptainer documentation. Have you tried going to that URL and following the instructions there?

I'm closing this issue as it seems to have been problems with your system rather than an issue with el_gato.

Alan

**Closed as completed by Alan-Collins** 2023-06-01 19:50 UTC
